name: ghostide Debug

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/build.yml
      - app/**
      - build.gradle.kts
      - gradle.properties
      - gradlew
      - gradlew.bat
      - settings.gradle.kts
  pull_request:
    paths:
      - .github/workflows/build.yml
      - app/**
      - build.gradle.kts
      - gradle.properties
      - gradlew
      - gradlew.bat
      - settings.gradle.kts    

jobs:
  ghostide-debug-apk:
    name: Build ghostide Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      
      - name: Build with Gradle
        id: gradle_build_debug
        run: ./gradlew assembleDebug
        
      - name: Upload debug apk
        uses: actions/upload-artifact@v4
        with:
          name: ghostide-debug
          compression-level: 0
          path: app/build/outputs/apk/debug/app-debug.apk

  send:
    name: Send APK
    runs-on: ubuntu-latest
    needs: ghostide-debug-apk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get the last commit message
        id: get_commit_msg
        run: |
          commit_message=$(git log -1 --pretty=format:'%s')
          echo "::set-output name=message::$commit_message"

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: ghostide-debug
      
      - name: Send APK to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: -1002213084840
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          document: app-debug.apk
          disable_web_page_preview: false
          message: |
            *Build Success!*
            Repository: *${{ github.repository }}*
            Branch: *${{ github.ref_name }}*
            App: Robok IDE
            Commit message: ${{ github.event.head_commit.message }}
            [Check the logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})